# Generated by Django 5.1.3 on 2024-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
